//экшен для отправки запроса на сервер
export const GET_INGREDIENTS_API: 'GET_INGREDIENTS_API' = 'GET_INGREDIENTS_API';
//экшен для при получение положительного ответа от сервера
export const GET_INGREDIENTS_API_SUCCESS: 'GET_INGREDIENTS_API_SUCCESS' = 'GET_INGREDIENTS_API_SUCCESS';
//экшен для при получение отрицательно ответа от сервера
export const GET_INGREDIENTS_API_FAILED: 'GET_INGREDIENTS_API_FAILED' = 'GET_INGREDIENTS_API_FAILED';
//экшен для сборки ингредиентов для бургера
export const INGREDIENTS_IN_BURGER_CONSTRUCTOR: 'INGREDIENTS_IN_BURGER_CONSTRUCTOR' = 'INGREDIENTS_IN_BURGER_CONSTRUCTOR';
//экшен для сортировки ингредиентов для бургера
export const SORT_INGREDIENTS_IN_BURGER_CONSTRUCTOR: 'SORT_INGREDIENTS_IN_BURGER_CONSTRUCTOR' = 'SORT_INGREDIENTS_IN_BURGER_CONSTRUCTOR';
//экшен для удаления ингредиента из собираемого бургера
export const DELETE_INGREDIENTS_IN_BURGER_CONSTRUCTOR: 'DELETE_INGREDIENTS_IN_BURGER_CONSTRUCTOR' = 'DELETE_INGREDIENTS_IN_BURGER_CONSTRUCTOR';
//экшен для удаления всех ингредиентов из собираемого бургера
export const DELETE_ALL_INGREDIENTS_IN_BURGER_CONSTRUCTOR: 'DELETE_ALL_INGREDIENTS_IN_BURGER_CONSTRUCTOR' = 'DELETE_ALL_INGREDIENTS_IN_BURGER_CONSTRUCTOR';

export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSE: 'WS_CONNECTION_CLOSE' = 'WS_CONNECTION_CLOSE';
export const WS_GET_ORDERS: 'WS_GET_ORDERS' = 'WS_GET_ORDERS';

export const OPEN_SELECTED_INGREDIENT: 'OPEN_SELECTED_INGREDIENTS' = 'OPEN_SELECTED_INGREDIENTS';
export const CLOSE_MODALS: 'CLOSE_SELECTED_INGREDIENT' = 'CLOSE_SELECTED_INGREDIENT';
export const OPEN_ORDER_DETAILS: 'OPEN_ORDER_DETAILS' = 'OPEN_ORDER_DETAILS';
export const OPEN_BURGER_DETAILS: 'OPEN_BURGER_DETAILS' = 'OPEN_BURGER_DETAILS';
export const OPEN_ORDER_ERROR: 'OPEN_ORDER_ERROR' = 'OPEN_ORDER_ERROR';

export const GET_ORDER_DETAILS: 'GET_ORDER_DETAILS' = 'GET_ORDER_DETAILS';
export const GET_ORDER_DETAILS_SUCCESS: 'GET_ORDER_DETAILS_SUCCESS' = 'GET_ORDER_DETAILS_SUCCESS';
export const GET_ORDER_DETAILS_SUCCESS_FAILED: 'GET_ORDER_DETAILS_SUCCESS_FAILED' = 'GET_ORDER_DETAILS_SUCCESS_FAILED';
export const CALC_PRICE_ORDER_DETAILS: 'CALC_PRICE_ORDER_DETAILS' = 'CALC_PRICE_ORDER_DETAILS';
export const SET_SELECTED_ID_INGREDIENTS: 'SET_SELECTED_ID_INGREDIENTS' = 'SET_SELECTED_ID_INGREDIENTS';
export const GET_USER_ORDER_DETAILS: 'GET_USER_ORDER_DETAILS' = 'GET_USER_ORDER_DETAILS';
export const GET_USER_ORDER_DETAILS_SUCCESS: 'GET_USER_ORDER_DETAILS_SUCCESS' = 'GET_USER_ORDER_DETAILS_SUCCESS';
export const GET_USER_ORDER_DETAILS_SUCCESS_FAILED: 'GET_USER_ORDER_DETAILS_SUCCESS_FAILED' = 'GET_USER_ORDER_DETAILS_SUCCESS_FAILED';

export const SUCCESS_AUTH: 'SUCCESS_AUTH' = 'SUCCESS_AUTH';
export const AUTH_REQUEST_SUCCESS: 'AUTH_REQUEST_SUCCESS' = 'AUTH_REQUEST_SUCCESS';
export const AUTH_REQUEST_FAILED: 'AUTH_REQUEST_FAILED' = 'AUTH_REQUEST_FAILED';
export const GET_REQUEST: 'GET_REQUEST' = 'GET_REQUEST';
export const GET_USER_REQUEST_SUCCESS: 'GET_USER_REQUEST_SUCCESS' = 'GET_USER_REQUEST_SUCCESS';
export const GET_USER_REQUEST_FAILED: 'GET_USER_REQUEST_FAILED' = 'GET_USER_REQUEST_FAILED';
export const REFRESH_ACCESS_TOKEN_REQUEST: 'REFRESH_ACCESS_TOKEN_REQUEST' = 'REFRESH_ACCESS_TOKEN_REQUEST';
export const REFRESH_ACCESS_TOKEN_REQUEST_SUCCESS: 'REFRESH_ACCESS_TOKEN_REQUEST_SUCCESS' = 'REFRESH_ACCESS_TOKEN_REQUEST_SUCCESS';
export const REFRESH_ACCESS_TOKEN_REQUEST_FAILED: 'REFRESH_ACCESS_TOKEN_REQUEST_FAILED' = 'REFRESH_ACCESS_TOKEN_REQUEST_FAILED';
export const PATCH_USER_REQUEST: 'PATCH_USER_REQUEST' = 'PATCH_USER_REQUEST';
export const PATCH_USER_REQUEST_SUCCESS: 'PATCH_USER_REQUEST_SUCCESS' = 'PATCH_USER_REQUEST_SUCCESS';
export const PATCH_USER_REQUEST_FAILED: 'PATCH_USER_REQUEST_FAILED' = 'PATCH_USER_REQUEST_FAILED';
export const EXIT_REQUEST: 'EXIT_REQUEST' = 'EXIT_REQUEST';
export const EXIT_REQUEST_SUCCESS: 'EXIT_REQUEST_SUCCESS' = 'EXIT_REQUEST_SUCCESS';
export const EXIT_REQUEST_FAILED: 'EXIT_REQUEST_FAILED' = 'EXIT_REQUEST_FAILED';
export const CANCEL_EDIT_USER: 'CANCEL_USER_EDIT' = 'CANCEL_USER_EDIT';
